# src/ch1_getting_started/Makefile

# If TOP isn't defined by the root Makefile, calculate it relative to here
TOP ?= $(shell cd ../.. && pwd)
TOOLS = copy charcount linecount wordcount detab sentencecount

include $(TOP)/common.mk